### ISSUE TITLE
Murder Mystery Project Summary & Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [AMABDULLAH/pwp-capstones#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ All of your code is valid and runs without throwing errors. 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ You implemented all of the necessary functions and the TextSample class. Well done!
### Criteria 3: Software Architecture
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ The code is divided up into functions appropriately.
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ You consistently use Python language features where appropriate. Good job!
### Criteria 5: Produces Accurate Output
* _Score Level:_ 2/4 (Approaches Expectations)
* _Comment(s):_ Most of your functions work properly, but there are little issues with the prepare_text() and get_average_sentence_length() functions that cause the similarity scores to be off. In the prepare_text() function, we need to account for exclamation points just like all the other punctuation marks, so we should have a line to remove those. In the get_average_sentence_length() function, there are two issues. One, some of the sentences in sentences_in_text have spaces at the beginning (eg ' Sure you think you know him!'), and using sentence.split(' ') will split on those leading spaces and add blank words to the words list, throwing the word count off. The default behavior of split() (ie sentence.split() without specifying to split on ' ') will handle these leading spaces better and avoid creating blank words. Two, there are some empty sentences in the sentences_in_text list, primarily because splitting on the final period in each text sample adds a blank item to the end of the list, but also due to an instance of double punctuation in the murder note (there is a '?!' which is converted to '..' and then split up). We can avoid this by checking if sentence exists ('if sentence:') before executing any of the other lines inside the 'for sentence in sentences_in_text:' loop.
### Overall Score: 18/20 (Meets Expectations)
Nice work on this project! Apart from the few small issues mentioned in the comments for Criteria 5, your code does what it is supposed to. It looks like you tested all of your functions, which is great, but I would encourage you to take this testing a little further by printing out some of the variables in the intermediary steps to see what they are doing, as this can make it easier see if more complex functions are working properly. For example, printing out the 'words' variable inside the 'for sentence in sentences_in_text:' loop in the get_average_sentence_length() function would show the blank words being added to the list, which would make the errors in this function easier to catch. (Do be sure to remove these sorts of print statements after you are finished testing, though). Again, well done with this!

**Comment by AMABDULLAH** [comment]
Thanks so much for your comments. These are very helpful.
